-- =============================================================================
-- PROYECTO: SIDEP (Sistema de Gestión de Emergencias)
-- MOTOR: Oracle Database 21c - DDL CORREGIDO PARA DATA MODELER
-- =============================================================================

-- Limpieza de tablas previas para evitar conflictos
DROP TABLE configuracion_sistema CASCADE CONSTRAINTS;
DROP TABLE actividad_usuario CASCADE CONSTRAINTS;
DROP TABLE asistencia_personal CASCADE CONSTRAINTS;
DROP TABLE carro CASCADE CONSTRAINTS;
DROP TABLE bolso_trauma CASCADE CONSTRAINTS;
DROP TABLE catalogo_cargo_oficialidad CASCADE CONSTRAINTS;
DROP TABLE catalogo_clave_emergencia CASCADE CONSTRAINTS;
DROP TABLE catalogo_estado_licencia CASCADE CONSTRAINTS;
DROP TABLE catalogo_estado_parte CASCADE CONSTRAINTS;
DROP TABLE catalogo_estado_voluntario CASCADE CONSTRAINTS;
DROP TABLE catalogo_grupo_sanguineo CASCADE CONSTRAINTS;
DROP TABLE catalogo_material CASCADE CONSTRAINTS;
DROP TABLE catalogo_tipo_voluntario CASCADE CONSTRAINTS;
DROP TABLE catalogo_tipo_bolso CASCADE CONSTRAINTS;
DROP TABLE catalogo_triage CASCADE CONSTRAINTS;
DROP TABLE checklist_carro CASCADE CONSTRAINTS;
DROP TABLE checklist_bolso_trauma CASCADE CONSTRAINTS;
DROP TABLE licencia_medica CASCADE CONSTRAINTS;
DROP TABLE material_por_carro CASCADE CONSTRAINTS;
DROP TABLE paciente_emergencia CASCADE CONSTRAINTS;
DROP TABLE parte_emergencia CASCADE CONSTRAINTS;
DROP TABLE rol_usuario CASCADE CONSTRAINTS;
DROP TABLE unidad_en_emergencia CASCADE CONSTRAINTS;
DROP TABLE vehiculo_civil_emergencia CASCADE CONSTRAINTS;
DROP TABLE otras_companias_emergencia CASCADE CONSTRAINTS;
DROP TABLE apoyo_externo_emergencia CASCADE CONSTRAINTS;
DROP TABLE usuario CASCADE CONSTRAINTS;

-- 1. TABLAS MAESTRAS (CATÁLOGOS)
CREATE TABLE catalogo_cargo_oficialidad ( id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, codigo VARCHAR2(50) UNIQUE NOT NULL, nombre VARCHAR2(100) NOT NULL, activo NUMBER(1) DEFAULT 1 );
CREATE TABLE catalogo_clave_emergencia ( id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, codigo VARCHAR2(50) UNIQUE NOT NULL, nombre VARCHAR2(100) NOT NULL, descripcion VARCHAR2(255), activo NUMBER(1) DEFAULT 1 );
CREATE TABLE catalogo_estado_licencia ( id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, codigo VARCHAR2(50) UNIQUE NOT NULL, nombre VARCHAR2(100) NOT NULL, descripcion VARCHAR2(255), activo NUMBER(1) DEFAULT 1 );
CREATE TABLE catalogo_estado_parte ( id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, codigo VARCHAR2(50) UNIQUE NOT NULL, nombre VARCHAR2(100) NOT NULL, descripcion VARCHAR2(255), activo NUMBER(1) DEFAULT 1 );
CREATE TABLE catalogo_estado_voluntario ( id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, codigo VARCHAR2(50) UNIQUE NOT NULL, nombre VARCHAR2(100) NOT NULL, activo NUMBER(1) DEFAULT 1 );
CREATE TABLE catalogo_grupo_sanguineo ( id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, codigo VARCHAR2(50) UNIQUE NOT NULL, nombre VARCHAR2(100) NOT NULL, activo NUMBER(1) DEFAULT 1 );
CREATE TABLE catalogo_material ( id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, codigo VARCHAR2(50) UNIQUE NOT NULL, nombre VARCHAR2(100) NOT NULL, categoria VARCHAR2(100), unidad VARCHAR2(50), activo NUMBER(1) DEFAULT 1 );
CREATE TABLE catalogo_tipo_voluntario ( id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, codigo VARCHAR2(50) UNIQUE NOT NULL, nombre VARCHAR2(100) NOT NULL, activo NUMBER(1) DEFAULT 1 );
CREATE TABLE catalogo_tipo_bolso ( id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, codigo VARCHAR2(50) UNIQUE NOT NULL, nombre VARCHAR2(100) NOT NULL, activo NUMBER(1) DEFAULT 1 );
CREATE TABLE catalogo_triage ( id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, codigo VARCHAR2(50) UNIQUE NOT NULL, nombre VARCHAR2(100) NOT NULL, color VARCHAR2(50), activo NUMBER(1) DEFAULT 1 );
CREATE TABLE rol_usuario ( id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, codigo VARCHAR2(50) UNIQUE NOT NULL, nombre VARCHAR2(100) NOT NULL, activo NUMBER(1) DEFAULT 1 );

-- 2. USUARIOS Y CARROS
CREATE TABLE usuario ( 
     rut                  VARCHAR2(20) PRIMARY KEY, 
     nombres              VARCHAR2(100) NOT NULL, 
     apellido_paterno     VARCHAR2(100) NOT NULL, 
     apellido_materno     VARCHAR2(100) NOT NULL, 
     email                VARCHAR2(150) UNIQUE NOT NULL, 
     password             VARCHAR2(255) NOT NULL, 
     firma_imagen         CLOB, 
     foto_perfil          CLOB, 
     rol_id               NUMBER NOT NULL REFERENCES rol_usuario(id), 
     cargo_id             NUMBER REFERENCES catalogo_cargo_oficialidad(id), 
     tipo_voluntario_id   NUMBER REFERENCES catalogo_tipo_voluntario(id), 
     estado_voluntario_id NUMBER REFERENCES catalogo_estado_voluntario(id), 
     grupo_sanguineo_id   NUMBER REFERENCES catalogo_grupo_sanguineo(id), 
     compania             VARCHAR2(100), 
     cuerpo_bombero       VARCHAR2(150) DEFAULT 'Cuerpo de Bomberos', 
     activo               NUMBER(1) DEFAULT 1 
);

CREATE TABLE carro ( 
     id               VARCHAR2(36) DEFAULT SYS_GUID() PRIMARY KEY, 
     patente          VARCHAR2(20) UNIQUE, 
     nomenclatura     VARCHAR2(50) UNIQUE NOT NULL, 
     nombre           VARCHAR2(100) NOT NULL, 
     marca            VARCHAR2(100), 
     kilometraje      NUMBER(10,1) DEFAULT 0, 
     estado_operativo NUMBER(1) DEFAULT 1 
);

CREATE TABLE bolso_trauma (
    id                   VARCHAR2(36) DEFAULT SYS_GUID() PRIMARY KEY,
    tipo_id              NUMBER NOT NULL REFERENCES catalogo_tipo_bolso(id),
    carro_id             VARCHAR2(36) NOT NULL REFERENCES carro(id) ON DELETE CASCADE,
    nombre_identificador VARCHAR2(100), 
    activo               NUMBER(1) DEFAULT 1 
);

-- 3. PARTE DE EMERGENCIA
CREATE TABLE parte_emergencia ( 
     id                 VARCHAR2(36) DEFAULT SYS_GUID() PRIMARY KEY, 
     correlativo        VARCHAR2(50) UNIQUE NOT NULL, 
     estado_id          NUMBER NOT NULL REFERENCES catalogo_estado_parte(id), 
     fecha_emergencia   TIMESTAMP WITH TIME ZONE NOT NULL, 
     clave_id           NUMBER NOT NULL REFERENCES catalogo_clave_emergencia(id), 
     obac_rut           VARCHAR2(20) NOT NULL REFERENCES usuario(rut), 
     direccion          VARCHAR2(200) NOT NULL, 
     referencia_lugar   VARCHAR2(255), 
     trabajo_realizado  CLOB, 
     material_utilizado CLOB, 
     metadata           CLOB CHECK (metadata IS JSON), 
     firma_obac         CLOB, 
     created_at         TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP 
);

CREATE TABLE unidad_en_emergencia ( 
     id            VARCHAR2(36) DEFAULT SYS_GUID() PRIMARY KEY, 
     parte_id      VARCHAR2(36) NOT NULL REFERENCES parte_emergencia(id) ON DELETE CASCADE, 
     carro_id      VARCHAR2(36) NOT NULL REFERENCES carro(id), 
     conductor_rut VARCHAR2(20) REFERENCES usuario(rut), 
     hora_6_0      VARCHAR2(10), 
     hora_6_3      VARCHAR2(10), 
     km_salida     NUMBER(10,1), 
     km_llegada    NUMBER(10,1)
);

CREATE TABLE vehiculo_civil_emergencia ( 
     id            VARCHAR2(36) DEFAULT SYS_GUID() PRIMARY KEY, 
     parte_id      VARCHAR2(36) NOT NULL REFERENCES parte_emergencia(id) ON DELETE CASCADE, 
     patente       VARCHAR2(20), 
     marca         VARCHAR2(50), 
     conductor     VARCHAR2(150), 
     rut_conductor VARCHAR2(20) 
);

CREATE TABLE paciente_emergencia ( 
     id            VARCHAR2(36) DEFAULT SYS_GUID() PRIMARY KEY, 
     parte_id      VARCHAR2(36) NOT NULL REFERENCES parte_emergencia(id) ON DELETE CASCADE, 
     nombre        VARCHAR2(150), 
     rut_paciente  VARCHAR2(20), 
     estado_triage VARCHAR2(50) 
);

CREATE TABLE asistencia_personal ( 
     id             VARCHAR2(36) DEFAULT SYS_GUID() PRIMARY KEY, 
     parte_id       VARCHAR2(36) NOT NULL REFERENCES parte_emergencia(id) ON DELETE CASCADE, 
     usuario_rut    VARCHAR2(20) NOT NULL REFERENCES usuario(rut)
);

-- 4. LOGÍSTICA
CREATE TABLE checklist_carro ( 
     id             VARCHAR2(36) DEFAULT SYS_GUID() PRIMARY KEY, 
     carro_id       VARCHAR2(36) NOT NULL REFERENCES carro(id), 
     cuartelero_rut VARCHAR2(20) NOT NULL REFERENCES usuario(rut), 
     fecha          DATE DEFAULT TRUNC(SYSDATE), 
     detalle        CLOB CHECK (detalle IS JSON), 
     firma_oficial  CLOB 
);

CREATE TABLE checklist_bolso_trauma (
     id                     VARCHAR2(36) DEFAULT SYS_GUID() PRIMARY KEY,
     bolso_id               VARCHAR2(36) NOT NULL REFERENCES bolso_trauma(id),
     revisor_rut            VARCHAR2(20) NOT NULL REFERENCES usuario(rut),
     fecha                  DATE DEFAULT TRUNC(SYSDATE),
     detalle                CLOB CHECK (detalle IS JSON)
);