export type ChecklistTemplateMaterial = {
  nombre: string;
  cantidadRequerida: number;
};

export type ChecklistTemplateUbicacion = {
  nombre: string;
  materiales: ChecklistTemplateMaterial[];
};

export const CHECKLIST_UNIDAD_TEMPLATES: Record<string, ChecklistTemplateUbicacion[]> = {
  'R-1': [
    {
      nombre: 'Cabina Parte Delantera',
      materiales: [
        { nombre: 'Guía de Respuesta a emergencias con Materiales Peligrosos', cantidadRequerida: 1 },
        { nombre: 'Bitácora de la Unidad', cantidadRequerida: 1 },
        { nombre: 'Base de carga Radio Motorola DP4801e', cantidadRequerida: 2 },
        { nombre: 'Radio Portátil Motorola DP4801e', cantidadRequerida: 1 },
        { nombre: 'Bitácora de equipos motores', cantidadRequerida: 1 },
        { nombre: 'Foco frontal copiloto', cantidadRequerida: 1 },
        { nombre: 'Toma datos de la unidad', cantidadRequerida: 1 },
        { nombre: 'Desfibrilador Externo Automático (DEA) Zoll AED Plus', cantidadRequerida: 1 },
        { nombre: 'Bastón Eléctrico TAC-STICK Leader Volt', cantidadRequerida: 1 },
        { nombre: 'Radio Base Motorola DM4600e', cantidadRequerida: 1 },
        { nombre: 'Carpeta con documentos de la unidad', cantidadRequerida: 1 },
        { nombre: 'Carpeta con documentación ante accidentes de voluntarios', cantidadRequerida: 1 },
        { nombre: 'Carpeta con check list de la unidad', cantidadRequerida: 1 },
      ],
    },
    {
      nombre: 'Cabina Parte Trasera',
      materiales: [
        { nombre: 'Anemómetro', cantidadRequerida: 1 },
        { nombre: 'Binoculares Basmar 20 x 50', cantidadRequerida: 1 },
        { nombre: 'Estuche con tarjetas de Triage', cantidadRequerida: 1 },
        { nombre: 'Detector de gases Scott Leak Alert', cantidadRequerida: 1 },
        { nombre: 'Luz emergencia de la unidad', cantidadRequerida: 1 },
        { nombre: 'Botiquín de la unidad', cantidadRequerida: 1 },
        { nombre: 'Chaleco reflectante de seguridad', cantidadRequerida: 1 },
        { nombre: 'Cinta de seguridad', cantidadRequerida: 1 },
        { nombre: 'Cascos de Rescate', cantidadRequerida: 2 },
        { nombre: 'Equipos de respiración 2.2 MSA FireHawk M7', cantidadRequerida: 4 },
        { nombre: 'Máscaras para equipos de respiración MSA FireHawk M7', cantidadRequerida: 4 },
        { nombre: 'Estacas de fierro', cantidadRequerida: 4 },
        { nombre: 'Cilindros de cambio 2.2 MSA FireHawk M7', cantidadRequerida: 3 },
        { nombre: 'Frazadas', cantidadRequerida: 2 },
        { nombre: 'Parka reflectante conductor', cantidadRequerida: 1 },
      ],
    },
    {
      nombre: 'Cortina N°1',
      materiales: [
        { nombre: 'Tabla Espinal', cantidadRequerida: 6 },
        { nombre: 'Bolso de Trauma', cantidadRequerida: 2 },
        { nombre: 'Cilindro de Oxígeno 1000lt', cantidadRequerida: 1 },
        { nombre: 'Chalecos de Extricación', cantidadRequerida: 5 },
        { nombre: 'PediPack', cantidadRequerida: 1 },
        { nombre: 'Laterales', cantidadRequerida: 6 },
        { nombre: 'Cinta velcro XXL', cantidadRequerida: 1 },
        { nombre: 'Pulpos', cantidadRequerida: 6 },
        { nombre: 'Maletín RCP', cantidadRequerida: 1 },
        { nombre: 'Chocos cuartones', cantidadRequerida: 20 },
        { nombre: 'Cuñas planas', cantidadRequerida: 12 },
        { nombre: 'Cuñas escalonadas chicas', cantidadRequerida: 8 },
        { nombre: 'Cuñas biseladas cortas', cantidadRequerida: 7 },
        { nombre: 'Cuñas biseladas', cantidadRequerida: 16 },
      ],
    },
    {
      nombre: 'Cajonera N°1',
      materiales: [
        { nombre: 'Bolso de Trauma', cantidadRequerida: 1 },
        { nombre: 'Mochila de Trauma + Bolso de collares cervicales', cantidadRequerida: 1 },
        { nombre: 'Bolso de Férulas Adulto', cantidadRequerida: 2 },
        { nombre: 'Bolso de Férulas Pediátrico', cantidadRequerida: 1 },
        { nombre: 'Kit de estabilización', cantidadRequerida: 1 },
        { nombre: 'Cuñas escalonadas chicas', cantidadRequerida: 4 },
        { nombre: 'Cuñas biseladas grandes', cantidadRequerida: 2 },
        { nombre: 'Cuñas escalonadas grandes', cantidadRequerida: 3 },
      ],
    },
    {
      nombre: 'Cortina N°2',
      materiales: [
        { nombre: 'Sierra Sable Milwaukee Sawzall', cantidadRequerida: 1 },
        { nombre: 'Maleta Milwaukee con Taladro percutor y Atornillador de impacto', cantidadRequerida: 1 },
        { nombre: 'Bolso Kit de Triage', cantidadRequerida: 1 },
        { nombre: 'Maletín Comando de Incidentes', cantidadRequerida: 1 },
        { nombre: 'Escala telescópica', cantidadRequerida: 1 },
        { nombre: 'Bolso con kit para manejo de vidrios', cantidadRequerida: 1 },
        { nombre: 'Bolso con mantas cubre cortes', cantidadRequerida: 1 },
        { nombre: 'Motor equipo electrógeno', cantidadRequerida: 1 },
        { nombre: 'Control Torreta', cantidadRequerida: 1 },
        { nombre: 'Butaquera', cantidadRequerida: 2 },
        { nombre: 'Alcachofa', cantidadRequerida: 1 },
        { nombre: 'Malla filtro para alcachofa', cantidadRequerida: 1 },
        { nombre: 'Flotador metálico', cantidadRequerida: 1 },
        { nombre: 'Basurero desechos biológicos', cantidadRequerida: 1 },
        { nombre: 'Cuña metálica de la unidad', cantidadRequerida: 1 },
        { nombre: 'Reducción 150mm a 110mm', cantidadRequerida: 1 },
      ],
    },
    {
      nombre: 'Cortina N°3',
      materiales: [
        { nombre: 'Kit cojines de elevación Vetter', cantidadRequerida: 1 },
        { nombre: 'Motor equipo Holmatro', cantidadRequerida: 1 },
        { nombre: 'L metálica', cantidadRequerida: 1 },
        { nombre: 'RAM Holmatro', cantidadRequerida: 1 },
        { nombre: 'Juego de muelas y cadenas Holmatro', cantidadRequerida: 1 },
        { nombre: 'Mangueras hidráulicas equipo Holmatro', cantidadRequerida: 2 },
        { nombre: 'Expansor Holmatro', cantidadRequerida: 1 },
        { nombre: 'Cizalla Holmatro', cantidadRequerida: 1 },
        { nombre: 'Hacha de Bombero', cantidadRequerida: 1 },
        { nombre: 'Hacha de Leñador', cantidadRequerida: 1 },
        { nombre: 'Halligan', cantidadRequerida: 1 },
        { nombre: 'Maceta 8 lb', cantidadRequerida: 1 },
        { nombre: 'Armada americana 50mm', cantidadRequerida: 1 },
        { nombre: 'Bolso de cuerdas', cantidadRequerida: 1 },
        { nombre: 'Camilla SKED', cantidadRequerida: 1 },
        { nombre: 'Arnés de Seguridad', cantidadRequerida: 1 },
        { nombre: 'Eslingas', cantidadRequerida: 3 },
      ],
    },
    {
      nombre: 'Cortina N°4',
      materiales: [
        { nombre: 'Tira 70mm (alimentación)', cantidadRequerida: 1 },
        { nombre: 'Bidón de combustible 20lt', cantidadRequerida: 1 },
        { nombre: 'Llave de grifo', cantidadRequerida: 1 },
        { nombre: 'Llave Storz', cantidadRequerida: 2 },
        { nombre: 'Cuña metálica de la unidad', cantidadRequerida: 1 },
        { nombre: 'Unión Grifo', cantidadRequerida: 1 },
        { nombre: 'Motor Equipo Lukas', cantidadRequerida: 1 },
        { nombre: 'Expansor Lukas', cantidadRequerida: 1 },
        { nombre: 'Cizalla Lukas', cantidadRequerida: 1 },
        { nombre: 'RAM Lukas', cantidadRequerida: 1 },
        { nombre: 'L metálica Lukas', cantidadRequerida: 1 },
        { nombre: 'Juego de Cadenas LUKAS', cantidadRequerida: 1 },
        { nombre: 'Estabilizadores Laterales Holmatro', cantidadRequerida: 3 },
        { nombre: 'Trípode para focos electrógeno', cantidadRequerida: 2 },
        { nombre: 'Focos Led electrógeno', cantidadRequerida: 2 },
        { nombre: 'Maletín Anti AirBag', cantidadRequerida: 1 },
        { nombre: 'Caja de herramientas', cantidadRequerida: 1 },
        { nombre: 'Lona Azul', cantidadRequerida: 1 },
        { nombre: 'Camilla Scoop', cantidadRequerida: 1 },
        { nombre: 'Bidón combustible Lukas', cantidadRequerida: 1 },
        { nombre: 'Carrete de Extensión 25mts', cantidadRequerida: 2 },
        { nombre: 'Placa para desplazamiento de panel frontal', cantidadRequerida: 1 },
      ],
    },
    {
      nombre: 'Cajonera N°4 / Techo',
      materiales: [
        { nombre: 'Gata hidráulica de 20 ton', cantidadRequerida: 1 },
        { nombre: 'Extintor PQS 4Kg', cantidadRequerida: 1 },
        { nombre: 'Bolso llave de ruedas y levante de cabina', cantidadRequerida: 1 },
        { nombre: 'Triángulo de Seguridad', cantidadRequerida: 1 },
        { nombre: 'Manguera neumática', cantidadRequerida: 1 },
        { nombre: 'Escala Simple', cantidadRequerida: 1 },
        { nombre: 'Conos de seguridad', cantidadRequerida: 10 },
        { nombre: 'Neumático de repuesto', cantidadRequerida: 1 },
        { nombre: 'Cuña Metálica', cantidadRequerida: 1 },
        { nombre: 'Motosierra', cantidadRequerida: 1 },
        { nombre: 'Casco para Motosierra', cantidadRequerida: 1 },
        { nombre: 'Bidón Motosierra', cantidadRequerida: 1 },
        { nombre: 'Bichero 1,8 mt', cantidadRequerida: 1 },
        { nombre: 'Escobillones', cantidadRequerida: 2 },
        { nombre: 'Pala antichispa', cantidadRequerida: 2 },
        { nombre: 'Pala', cantidadRequerida: 1 },
        { nombre: 'Techo Gabeta N°2 Chorizos', cantidadRequerida: 4 },
        { nombre: 'Techo Gabeta N°3 Sacos de Aserrín', cantidadRequerida: 2 },
      ],
    },
  ],
  'BX-1': [
    {
      nombre: 'Cabina',
      materiales: [
        { nombre: 'Equipo ERA 4.5 G1', cantidadRequerida: 4 },
        { nombre: 'Máscara', cantidadRequerida: 4 },
        { nombre: 'Botella de cambio 4.5 G1', cantidadRequerida: 4 },
        { nombre: 'Cinta de demarcación', cantidadRequerida: 1 },
        { nombre: 'Bastón Dieléctrico Leader Volt (WB226)(132019)', cantidadRequerida: 1 },
        { nombre: 'TIF8900 (Detector de gas) (Serial 5276879TIF)', cantidadRequerida: 1 },
        { nombre: 'GREE', cantidadRequerida: 1 },
        { nombre: 'Caja de herramientas', cantidadRequerida: 1 },
        { nombre: 'Casco motosierra', cantidadRequerida: 2 },
        { nombre: 'Caja de juguetes', cantidadRequerida: 1 },
        { nombre: 'Hacha de bomberos', cantidadRequerida: 1 },
        { nombre: 'Halligan', cantidadRequerida: 1 },
        { nombre: 'Maceta', cantidadRequerida: 1 },
        { nombre: 'Extractor de válvula de gas', cantidadRequerida: 1 },
        { nombre: 'Corta cables', cantidadRequerida: 1 },
        { nombre: 'Diablito', cantidadRequerida: 1 },
        { nombre: 'Hacha de leñador', cantidadRequerida: 1 },
        { nombre: 'Cinta milimétrica 50 mts', cantidadRequerida: 1 },
        { nombre: 'Estaquilla', cantidadRequerida: 4 },
        { nombre: 'Estaquilla ciega', cantidadRequerida: 3 },
        { nombre: 'Eslinga', cantidadRequerida: 1 },
        { nombre: 'Luz de emergencia', cantidadRequerida: 1 },
        { nombre: 'Radio Motorola DGP 5050e (Serial 807TTF4621)', cantidadRequerida: 1 },
        { nombre: 'Gata', cantidadRequerida: 1 },
        { nombre: 'Traba cabina', cantidadRequerida: 1 },
        { nombre: "Frasco O'ring", cantidadRequerida: 1 },
        { nombre: 'Chaleco reflectante', cantidadRequerida: 1 },
        { nombre: 'Guante rescate animal', cantidadRequerida: 1 },
        { nombre: 'Base Motorola DGM 5000 (Serial 511TQM3823)', cantidadRequerida: 1 },
        { nombre: 'Desfibrilador Externo Automático (DEA)', cantidadRequerida: 1 },
      ],
    },
    {
      nombre: 'Cortina 1',
      materiales: [
        { nombre: 'Foco de electrógeno', cantidadRequerida: 2 },
        { nombre: 'Carrete de electrógeno', cantidadRequerida: 2 },
        { nombre: 'Trípode', cantidadRequerida: 2 },
        { nombre: 'Tabla', cantidadRequerida: 3 },
        { nombre: 'Laterales', cantidadRequerida: 3 },
        { nombre: 'Pulpo', cantidadRequerida: 3 },
        { nombre: 'Bolso de trauma', cantidadRequerida: 2 },
        { nombre: 'Bolso de férula', cantidadRequerida: 1 },
        { nombre: 'Chaleco de extricación', cantidadRequerida: 1 },
      ],
    },
    {
      nombre: 'Cajonera 1',
      materiales: [
        { nombre: 'Electrógeno', cantidadRequerida: 1 },
        { nombre: 'Cuñas de unidad', cantidadRequerida: 2 },
        { nombre: 'Tubo extractor de gases', cantidadRequerida: 1 },
      ],
    },
    {
      nombre: 'Cortina 2',
      materiales: [
        { nombre: 'Motosierra', cantidadRequerida: 1 },
        { nombre: 'Bolso de cuerdas', cantidadRequerida: 1 },
        { nombre: 'Tendido simple (3 tiras de 50 mm + pitón Akron)', cantidadRequerida: 1 },
        { nombre: 'Bidón motosierra', cantidadRequerida: 1 },
      ],
    },
    {
      nombre: 'Cajonera 2',
      materiales: [{ nombre: 'Tendido simple (3 tiras de 50 mm + pitón Protek)', cantidadRequerida: 1 }],
    },
    {
      nombre: 'Cortina 3',
      materiales: [
        { nombre: 'Tira de 50 mm', cantidadRequerida: 2 },
        { nombre: 'Tira de 38 mm', cantidadRequerida: 4 },
        { nombre: 'Tira corta de 70 mm (abastecimiento)', cantidadRequerida: 1 },
        { nombre: 'Tendido simple (2 tiras de 70 mm + pitón Protek)', cantidadRequerida: 1 },
        { nombre: 'Cuña biselada grande', cantidadRequerida: 2 },
        { nombre: 'Cuña escalonada grande', cantidadRequerida: 5 },
        { nombre: 'Choco chico', cantidadRequerida: 1 },
        { nombre: 'Choco mediano', cantidadRequerida: 1 },
      ],
    },
    {
      nombre: 'Cajonera 3',
      materiales: [
        { nombre: 'Pitón Protek 70 mm', cantidadRequerida: 1 },
        { nombre: 'Pitón Akron 50 mm', cantidadRequerida: 1 },
        { nombre: 'Pitón Scotty 38 mm', cantidadRequerida: 1 },
        { nombre: 'Reducción 130-110 mm', cantidadRequerida: 1 },
        { nombre: 'Reducción 110-70 mm', cantidadRequerida: 1 },
        { nombre: 'Reducción 50-38 mm', cantidadRequerida: 1 },
        { nombre: 'Llave Storz', cantidadRequerida: 2 },
        { nombre: 'Llave de grifo', cantidadRequerida: 1 },
        { nombre: 'Unión grifo', cantidadRequerida: 1 },
        { nombre: 'Pitón forestal', cantidadRequerida: 1 },
        { nombre: 'Alcachofa', cantidadRequerida: 1 },
      ],
    },
    {
      nombre: 'Cortina 4',
      materiales: [
        { nombre: 'Equipo ERA 4.5 G1', cantidadRequerida: 2 },
        { nombre: 'Máscara', cantidadRequerida: 2 },
        { nombre: 'Botella de cambio 4.5 G1', cantidadRequerida: 2 },
        { nombre: 'Escala telescópica', cantidadRequerida: 1 },
        { nombre: 'Pala', cantidadRequerida: 3 },
        { nombre: 'McLeod', cantidadRequerida: 4 },
        { nombre: 'Rastrillo cegador', cantidadRequerida: 1 },
        { nombre: 'Pulaski', cantidadRequerida: 1 },
        { nombre: 'Rozón', cantidadRequerida: 1 },
        { nombre: 'Escoba industrial', cantidadRequerida: 1 },
        { nombre: 'Kit cojines de elevación (maletín + 3 cojines)', cantidadRequerida: 1 },
        { nombre: 'Saco aserrín', cantidadRequerida: 1 },
        { nombre: 'Bidón rojo', cantidadRequerida: 1 },
        { nombre: 'Lukas Combi (motor + cizalla/expansor + RAM + cadenas)', cantidadRequerida: 1 },
      ],
    },
    {
      nombre: 'Cajonera 4',
      materiales: [
        { nombre: 'Motobomba', cantidadRequerida: 1 },
        { nombre: 'Extintor', cantidadRequerida: 1 },
        { nombre: 'Caja de herramientas de motosierra', cantidadRequerida: 1 },
        { nombre: 'Alcachofa', cantidadRequerida: 1 },
        { nombre: 'Malla de alcachofa', cantidadRequerida: 1 },
      ],
    },
    {
      nombre: 'Techo',
      materiales: [
        { nombre: 'Chorizo', cantidadRequerida: 4 },
        { nombre: 'Bichero 3 mts', cantidadRequerida: 1 },
        { nombre: 'Cono', cantidadRequerida: 7 },
        { nombre: 'Escala simple', cantidadRequerida: 1 },
      ],
    },
  ],
  'B-1': [
    {
      nombre: 'Cabina',
      materiales: [
        { nombre: 'ERA M7', cantidadRequerida: 4 },
        { nombre: 'Máscaras ERA', cantidadRequerida: 4 },
        { nombre: 'Cilindros 4.5 M7', cantidadRequerida: 5 },
        { nombre: 'Cilindro G1', cantidadRequerida: 2 },
        { nombre: 'Bastón eléctrico Leader Volt', cantidadRequerida: 1 },
        { nombre: 'Bitácora unidad', cantidadRequerida: 1 },
        { nombre: 'Radio Base Motorola DGM 5000', cantidadRequerida: 1 },
        { nombre: 'Cámara térmica', cantidadRequerida: 1 },
        { nombre: 'Cinta de peligro', cantidadRequerida: 1 },
        { nombre: 'Radio OBAC DGP 8550e', cantidadRequerida: 1 },
        { nombre: 'Batería repuesto foco', cantidadRequerida: 1 },
        { nombre: 'Bolso oxígeno', cantidadRequerida: 1 },
      ],
    },
    {
      nombre: 'Cortina 1',
      materiales: [
        { nombre: 'Cuerda', cantidadRequerida: 1 },
        { nombre: 'Ventilador', cantidadRequerida: 1 },
        { nombre: 'Bolso trauma', cantidadRequerida: 1 },
        { nombre: 'Manta de quemado', cantidadRequerida: 1 },
        { nombre: 'Kit de quemado', cantidadRequerida: 1 },
        { nombre: 'Motosierra', cantidadRequerida: 1 },
        { nombre: 'Tronzadora', cantidadRequerida: 1 },
        { nombre: 'Bidón motosierra', cantidadRequerida: 1 },
        { nombre: 'Casco motosierra', cantidadRequerida: 1 },
      ],
    },
    {
      nombre: 'Cajonera 1',
      materiales: [{ nombre: 'Tendido simple 4 tiras de 50 mm + pitón TFT', cantidadRequerida: 1 }],
    },
    {
      nombre: 'Cortina 2',
      materiales: [
        { nombre: 'Pitón monitor', cantidadRequerida: 1 },
        { nombre: 'ERA M7', cantidadRequerida: 2 },
        { nombre: 'Máscara M7', cantidadRequerida: 2 },
        { nombre: 'Tendido rápido de 5 tiras de 50 mm', cantidadRequerida: 1 },
        { nombre: 'Foco a batería', cantidadRequerida: 1 },
        { nombre: 'Frazada', cantidadRequerida: 1 },
        { nombre: 'Caja motosierrista (pierneras, llaves, guantes moto)', cantidadRequerida: 1 },
      ],
    },
    {
      nombre: 'Cajonera 2',
      materiales: [{ nombre: 'Tendido mixto con gemelo (2 tiras 70 mm + 3 tiras 50 mm + pitón Protek 50 mm)', cantidadRequerida: 1 }],
    },
    {
      nombre: 'Cortina 3',
      materiales: [
        { nombre: 'ERA G1', cantidadRequerida: 2 },
        { nombre: 'Máscaras ERA G1', cantidadRequerida: 2 },
        { nombre: 'Tira de 70', cantidadRequerida: 2 },
        { nombre: 'Tiras de 38', cantidadRequerida: 3 },
        { nombre: 'Tendido de 4 tiras de 50 mm + pitón TFT', cantidadRequerida: 1 },
        { nombre: 'Tiras de 50', cantidadRequerida: 5 },
      ],
    },
    {
      nombre: 'Cajonera 3',
      materiales: [{ nombre: 'Tendido mixto de 70 mm y 2 tiras de 50 + pitón TFT', cantidadRequerida: 1 }],
    },
    {
      nombre: 'Cortina 4',
      materiales: [
        { nombre: 'Halligan', cantidadRequerida: 2 },
        { nombre: 'Napoleón', cantidadRequerida: 1 },
        { nombre: 'TNT', cantidadRequerida: 1 },
        { nombre: 'Hacha de leñador', cantidadRequerida: 1 },
        { nombre: 'Hacha de bombero', cantidadRequerida: 2 },
        { nombre: 'Maceta', cantidadRequerida: 1 },
        { nombre: 'Diablo', cantidadRequerida: 1 },
        { nombre: 'Lavador de tiras', cantidadRequerida: 1 },
        { nombre: 'Pitón 50 mm (2 Protek + 1 Akron)', cantidadRequerida: 3 },
        { nombre: 'Pitón 70 mm (Protek)', cantidadRequerida: 1 },
        { nombre: 'Pitón forestal 50 mm', cantidadRequerida: 1 },
        { nombre: 'Llave de grifo', cantidadRequerida: 1 },
        { nombre: 'Llave de copla', cantidadRequerida: 2 },
        { nombre: 'Bichero NY', cantidadRequerida: 1 },
        { nombre: 'Extintor de agua', cantidadRequerida: 1 },
        { nombre: 'Boquilla de monitor', cantidadRequerida: 1 },
        { nombre: 'Lonas', cantidadRequerida: 2 },
      ],
    },
    {
      nombre: 'Techo / Bomba',
      materiales: [
        { nombre: 'Chorizos', cantidadRequerida: 3 },
        { nombre: 'Palas', cantidadRequerida: 2 },
        { nombre: 'Tabla', cantidadRequerida: 1 },
        { nombre: 'Pulpo', cantidadRequerida: 1 },
        { nombre: 'Par de laterales', cantidadRequerida: 1 },
        { nombre: 'Conos', cantidadRequerida: 6 },
        { nombre: 'Escalas de techo', cantidadRequerida: 2 },
        { nombre: 'Escala simple', cantidadRequerida: 1 },
        { nombre: 'Escala doble paño', cantidadRequerida: 1 },
        { nombre: 'Bichero 3 m', cantidadRequerida: 1 },
        { nombre: 'Bicheros 1.8 m', cantidadRequerida: 3 },
        { nombre: 'Alcachofa 110 mm', cantidadRequerida: 1 },
        { nombre: 'Rastrillo cegador', cantidadRequerida: 1 },
        { nombre: 'McLeod', cantidadRequerida: 4 },
        { nombre: 'Malla protectora alcachofa', cantidadRequerida: 1 },
        { nombre: 'Motobomba flotante', cantidadRequerida: 1 },
        { nombre: 'Neumático de repuesto', cantidadRequerida: 1 },
        { nombre: 'Fierro sujeta cabina', cantidadRequerida: 1 },
        { nombre: 'Tendido alimentación (3 tiras de 70 mm)', cantidadRequerida: 1 },
      ],
    },
  ],
};
