import { NgModule } from '@angular/core';
import {
  LucideAngularModule,
  AlertCircle,
  ArchiveX,
  ArrowLeft,
  Bell,
  Briefcase,
  Building2,
  Database,
  Calendar,
  CalendarDays,
  Car,
  ChartColumn,
  Check,
  CircleCheck,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Droplet,
  Eye,
  EyeOff,
  FileDown,
  FilePlus2,
  FileSpreadsheet,
  FileText,
  Flame,
  HeartPulse,
  History,
  Funnel,
  Key,
  LayoutDashboard,
  ImageDown,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Menu,
  MapPin,
  Package,
  Pencil,
  PenTool,
  Plus,
  PlusCircle,
  Phone,
  RefreshCw,
  Save,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  User,
  Users,
  Wrench,
  X,
  Tags,
} from 'lucide-angular';

// Extraemos la lista a una constante estática para que Angular compile sin errores
export const icons = {
  AlertCircle, ArchiveX, ArrowLeft, Bell, Briefcase, Building2, Check, Database, Calendar, CalendarDays,
  Car, ChartColumn, CircleCheck, ChevronDown, ChevronRight, ChevronUp,
  ClipboardCheck, ClipboardList, Clock, Droplet, Eye, EyeOff, FileDown, FilePlus2, FileSpreadsheet, FileText,
  Flame, HeartPulse, History, Funnel, ImageDown, Key, LayoutDashboard, Loader2, Lock, LogIn,
  LogOut, Mail, Menu, MapPin, Package, Pencil, PenTool, Phone, Plus, PlusCircle, RefreshCw, Save, Search,
  Send, Settings, Shield, ShieldCheck, TrendingDown, TrendingUp, TriangleAlert, Truck,
  User, Users, Wrench, X, Tags
};

@NgModule({
  imports: [LucideAngularModule.pick(icons)],
  exports: [LucideAngularModule]
})
export class SidepIconsModule {}