import { NgModule } from '@angular/core';
import {
  LucideAngularModule,
  ArrowLeft,
  Bell,
  Briefcase,
  Building2,
  Database,
  Calendar,
  CalendarDays,
  Car,
  ChartColumn,
  CircleCheck,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Download,
  Droplet,
  Eye,
  FileText,
  Flame,
  HeartPulse,
  History,
  Funnel,
  LayoutDashboard,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Menu,
  MapPin,
  Package,
  Pencil,
  Plus,
  Phone,
  Save,
  Search,
  Send,
  Settings,
  Shield,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Truck,
  User,
  Users,
  Wrench,
  X,
} from 'lucide-angular';

// Extraemos la lista a una constante estática para que Angular compile sin errores
export const icons = {
  ArrowLeft, Bell, Briefcase, Building2, Database, Calendar, CalendarDays,
  Car, ChartColumn, CircleCheck, ChevronDown, ChevronRight, ChevronUp,
  ClipboardCheck, ClipboardList, Clock, Download, Droplet, Eye, FileText,
  Flame, HeartPulse, History, Funnel, LayoutDashboard, Loader2, Lock, LogIn,
  LogOut, Mail, Menu, MapPin, Package, Pencil, Plus, Phone, Save, Search,
  Send, Settings, Shield, TrendingDown, TrendingUp, TriangleAlert, Truck,
  User, Users, Wrench, X
};

@NgModule({
  imports: [LucideAngularModule.pick(icons)],
  exports: [LucideAngularModule]
})
export class SidepIconsModule {}